# renew_before_expiry = 30 days
version = 3.3.0
archive_dir = /etc/letsencrypt/archive/arrisala.fr
cert = /etc/letsencrypt/live/arrisala.fr/cert.pem
privkey = /etc/letsencrypt/live/arrisala.fr/privkey.pem
chain = /etc/letsencrypt/live/arrisala.fr/chain.pem
fullchain = /etc/letsencrypt/live/arrisala.fr/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d0359887e55d98aa49e4f34e78db3312
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
grafana.arrisala.fr = /var/www/certbot
portainer.arrisala.fr = /var/www/certbot
